#!/bin/bash
/usr/bin/time -v --output=casestudies/roundrobin/exec_0.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_0.seq'  | tee casestudies/roundrobin/exec_0.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_1.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_1.seq'  | tee casestudies/roundrobin/exec_1.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_2.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_2.seq'  | tee casestudies/roundrobin/exec_2.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_3.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_3.seq'  | tee casestudies/roundrobin/exec_3.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_4.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_4.seq'  | tee casestudies/roundrobin/exec_4.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_5.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_5.seq'  | tee casestudies/roundrobin/exec_5.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_6.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_6.seq'  | tee casestudies/roundrobin/exec_6.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_7.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_7.seq'  | tee casestudies/roundrobin/exec_7.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_8.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_8.seq'  | tee casestudies/roundrobin/exec_8.txt

/usr/bin/time -v --output=casestudies/roundrobin/exec_9.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (r_0 && ! g_0 -> X r_0)' '-d=[]<> (! (r_1 && g_1))' '-d=[] (! r_0 && g_0 -> X (! r_0))' '-d=[] (! r_1 && g_1 -> X (! r_1))' '-d=[]<> (! (r_0 && g_0))' '-d=[] (r_1 && ! g_1 -> X r_1)' '-g=[] (! g_0 && true || (true && (! g_1)) && (r_0 && X r_1 -> X (X (g_0 && g_1))))' '-g=[] (r_0 -> <> g_0)' '-g=[] (r_1 -> <> g_1))' '-t=3600' '-s=aalta' '--seq=casestudies/roundrobin/exec_9.seq'  | tee casestudies/roundrobin/exec_9.txt

