name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install package
      run:
        mvn install:install-file -Dfile="./lib/ltl2buchi.jar" -DgroupId="gov.nasa.ltl" -DartifactId=ltl2buchi -Dversion=1.0 -Dpackaging=jar;
        mvn install:install-file -Dfile="./lib/rltlconv.jar" -DgroupId="de.uni_luebeck.isp" -DartifactId=rltlconv -Dversion=1.0 -Dpackaging=jar;
        mvn install:install-file -Dfile="./lib/JFLAP-7.0_With_Source.jar" -DgroupId="automata" -DartifactId=JFLAP -Dversion=1.0 -Dpackaging=jar
    - name: set LTL solver
      run: chmod +x aalta_linux; chmod +x pltl
    - name: Build with Maven
      run:
        mvn -DskipTests package
