#!/bin/bash
/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_0.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_0.seq'  | tee casestudies/prioritized_arbiter/exec_0.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_1.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_1.seq'  | tee casestudies/prioritized_arbiter/exec_1.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_2.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_2.seq'  | tee casestudies/prioritized_arbiter/exec_2.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_3.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_3.seq'  | tee casestudies/prioritized_arbiter/exec_3.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_4.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_4.seq'  | tee casestudies/prioritized_arbiter/exec_4.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_5.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_5.seq'  | tee casestudies/prioritized_arbiter/exec_5.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_6.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_6.seq'  | tee casestudies/prioritized_arbiter/exec_6.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_7.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_7.seq'  | tee casestudies/prioritized_arbiter/exec_7.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_8.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_8.seq'  | tee casestudies/prioritized_arbiter/exec_8.txt

/usr/bin/time -v --output=casestudies/prioritized_arbiter/exec_9.time timeout 3601 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (<> (! r_m))' '-g=[] (r_m -> X ((! g_0 && ! g_1) U g_m))' '-g=[] (! g_0 && true || (true && (! g_1)))' '-g=[] (! (g_m && g_0))' '-g=[] (! (g_m && g_1))' '-g=[] (r_0 -> <> g_0) && [] (r_1 -> <> g_1)' '-g=[] (r_0 && X r_1 -> X (X (g_0 && g_1)))' '-t=3600' '-s=aalta' '--seq=casestudies/prioritized_arbiter/exec_9.seq'  | tee casestudies/prioritized_arbiter/exec_9.txt

