#!/bin/bash
/usr/bin/time -v --output=casestudies/liftcontroller/exec_0.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_0.seq'  | tee casestudies/liftcontroller/exec_0.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_1.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_1.seq'  | tee casestudies/liftcontroller/exec_1.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_2.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_2.seq'  | tee casestudies/liftcontroller/exec_2.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_3.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_3.seq'  | tee casestudies/liftcontroller/exec_3.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_4.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_4.seq'  | tee casestudies/liftcontroller/exec_4.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_5.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_5.seq'  | tee casestudies/liftcontroller/exec_5.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_6.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_6.seq'  | tee casestudies/liftcontroller/exec_6.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_7.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_7.seq'  | tee casestudies/liftcontroller/exec_7.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_8.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_8.seq'  | tee casestudies/liftcontroller/exec_8.txt

/usr/bin/time -v --output=casestudies/liftcontroller/exec_9.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=!b1 && !b2 && !b3' '-d=[]((b1 && f1) -> X(!b1))' '-d=[]((b2 && f2) -> X(!b2))' '-d=[]((b3 && f3) -> X(!b3))' '-d=[]((b1 && !f1) -> X(b1))' '-d=[]((b2 && !f2) -> X(b2))' '-d=[]((b3 && !f3) -> X(b3))' '-g=f1 && !f2 && !f3' '-g=[](!(f1 && f2) && !(f1 && f3) && !(f2 && f3))' '-g=[](f1 -> X (f1 || f2))' '-g=[](f2 -> X (f1 || f2 || f3))' '-g=[](f3 -> X (f2 || f3))' '-g=[](((f1 && X(f2)) || (f2 && X(f3))) -> X (b1 || b2 || b3))' '-g=[]<>(b1 -> f1)' '-g=[]<>(b2 -> f2)' '-g=[]<>(b3 -> f3)' '-g=[]<>(f1)' '-g=[]<>(f2)' '-g=[]<>(f3)' '-t=36000' '-s=aalta' '--seq=casestudies/liftcontroller/exec_9.seq'  | tee casestudies/liftcontroller/exec_9.txt

