#!/bin/bash
/usr/bin/time -v --output=casestudies/loadbalancer/exec_0.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_0.seq'  | tee casestudies/loadbalancer/exec_0.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_1.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_1.seq'  | tee casestudies/loadbalancer/exec_1.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_2.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_2.seq'  | tee casestudies/loadbalancer/exec_2.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_3.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_3.seq'  | tee casestudies/loadbalancer/exec_3.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_4.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_4.seq'  | tee casestudies/loadbalancer/exec_4.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_5.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_5.seq'  | tee casestudies/loadbalancer/exec_5.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_6.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_6.seq'  | tee casestudies/loadbalancer/exec_6.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_7.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_7.seq'  | tee casestudies/loadbalancer/exec_7.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_8.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_8.seq'  | tee casestudies/loadbalancer/exec_8.txt

/usr/bin/time -v --output=casestudies/loadbalancer/exec_9.time timeout 36001 java -Xmx8g -ea -jar ./target/LOGION-run.jar '-d=[] (idle && X (! grant_0 && ! grant_1) -> X idle)' '-d=[] (<> idle)' '-d=[] (X (! grant_0) || X ((! request_0 && ! idle) U (! request_0 && idle)))' '-g=[](X grant_1 -> request_1)' '-g=! <> ([] (request_0 && X (! grant_0)))' '-g=! <> ([] (request_1 && X (! grant_1)))' '-g=[] (X (! grant_0 && true || (true && (! grant_1))))' '-g=[](request_0 && X request_1 -> X (X (grant_0 && grant_1)))' '-g=[](! idle -> X (! grant_0 && ! grant_1))' '-g=[](request_0 -> grant_1)' '-g=[](X grant_0 -> request_0)' '-t=36000' '-s=aalta' '--seq=casestudies/loadbalancer/exec_9.seq'  | tee casestudies/loadbalancer/exec_9.txt

